spring:
  profiles:
    active: dev

  jackson:
    # 时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区
    time-zone:
      UTC

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cadmin?useUnicode=true&charsetEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8081

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
